class Canvas:
    def get_context(self, context_type: str) -> Context: ...
    def clear(self) -> None: ...
    def draw_bounding_boxes(self, detections: list) -> None: ...
    def draw_pose(self, pose: list) -> None: ...
    def draw_poses(self, poses: list) -> None: ...
    def draw_hand(self, hand: dict) -> None: ...
    def draw_hands(self, hands: list) -> None: ...

class Context:
    fill_style: str
    stroke_style: str
    line_width: float
    font: str
    def begin_path(self) -> None: ...
    def arc(self, x: float, y: float, radius: float, start_angle: float, end_angle: float) -> None: ...
    def fill(self) -> None: ...
    def stroke(self) -> None: ...
    def fill_text(self, text: str, x: float, y: float) -> None: ...
    def stroke_rect(self, x: float, y: float, width: float, height: float) -> None: ...
    def fill_rect(self, x: float, y: float, width: float, height: float) -> None: ...
    def clear_rect(self, x: float, y: float, width: float, height: float) -> None: ...

class Colors:
    BLACK: str
    WHITE: str
    RED: str
    GREEN: str
    BLUE: str
    YELLOW: str
    CYAN: str
    MAGENTA: str
    ORANGE: str
    PURPLE: str
    PINK: str
    BROWN: str
    GRAY: str
    GREY: str
    LIGHT_GRAY: str
    LIGHT_GREY: str
    DARK_GRAY: str
    DARK_GREY: str

colors: Colors

def canvas(width: int = 0, height: int = 0) -> Canvas: ...
def draw_image(canvas: Canvas, path: str) -> None: ...
