class Canvas:
    def draw_bounding_boxes(self, faces: list) -> None: ...

class Camera:
    def stop(self) -> None: ...

class Detector:
    def get_detections(self) -> list: ...
    def stop(self) -> None: ...

def get_canvas(width: int, height: int) -> Canvas: ...
def start_camera(canvas: Canvas) -> Camera: ...
def start_detector(camera: Camera) -> Detector: ...
