from graphics import Canvas

class Camera:
    def stop(self) -> None: ...

class Detector:
    def get_detections(self) -> list: ...
    def stop(self) -> None: ...

def start_camera(canvas: Canvas | None = None) -> Camera: ...
def start_face_detector(camera: Camera) -> Detector: ...
def start_object_detector(camera: Camera, delegate: str = "CPU") -> Detector: ...
