from typing import Any, Callable

class Sky:
    CLOUDS: str
    DEEP_SPACE: str
    MODERN_BUILDINGS: str
    ORLANDO_STADIUM: str
    PURE_SKY: str

class DOMProxy:
    def __getattr__(self, name: str) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...

class Mesh:
    def set_position(self, x: float = 0, y: float = 0, z: float = 0) -> "Mesh": ...
    def set_rotation(self, x: float = 0, y: float = 0, z: float = 0) -> "Mesh": ...
    def set_color(self, color: str) -> "Mesh": ...
    def set_texture(self, source: str) -> "Mesh": ...
    def set_scale(self, x: float = 1, y: float = 1, z: float = 1) -> "Mesh": ...
    def on_click(self, fn: Callable[[], None]) -> "Mesh": ...

class Scene:
    def set_sky(self, color: str = "#87CEEB") -> "Scene":
        """Set the sky to a hex colour (e.g. "#87CEEB") or an environment map (e.g. scene3d.Sky.CLOUDS)."""
        ...
    def set_ground(self, length: float = 10, width: float = 10) -> "Scene": ...
    def add(self, mesh: Mesh) -> "Scene": ...
    def get_context(self, ctx_type: str = "2d") -> DOMProxy: ...
    def on_frame(self, fn: Callable[[float], None]) -> Callable[[float], None]: ...
    def run(self) -> None: ...

class _Shapes:
    @staticmethod
    def Box(width: float = 1, height: float = 1, depth: float = 1) -> Mesh: ...
    @staticmethod
    def Sphere(diameter: float = 1, segments: int = 16) -> Mesh: ...
    @staticmethod
    def Cylinder(diameter: float = 1, height: float = 1, tessellation: int = 24) -> Mesh: ...

Shapes: _Shapes
